### ISSUE TITLE
Update `o-ft-icons` dependents to use `o-icons`

### ISSUE THREAD

**Issue by onishiweb** [Financial-Times/o-icons#14]
Dependents:
- [x] next-sass-setup
- [x] o-author-alerts
- [x] o-buttons
- [x] o-card
- [x] o-chat
- [x] o-comment-ui
- [x] o-expander
- [x] o-gallery
- [x] o-header
- [x] o-hierarchical-nav

**Comment by onishiweb** [comment]
o-gallery: https://github.com/Financial-Times/o-gallery/pull/56
o-hierarchical-nav: https://github.com/Financial-Times/o-hierarchical-nav/pull/65

**Comment by onishiweb** [comment]
o-expander: https://github.com/Financial-Times/o-expander/pull/31

**Comment by onishiweb** [comment]
o-buttons: https://github.com/Financial-Times/o-buttons/pull/79

**Comment by onishiweb** [comment]
@wheresrhys once the final PR (for `o-buttons`) is merged that's all of the Origami components updated to use `o-icons`, just need whatever's remaining in #11 and then `next-sass-setup` can be updated which I think is what will mean your switch to `o-icons` :)

**Comment by wheresrhys** [comment]
cool. I think, as next-sass-setup only included o-ft-icons in order to switch it off, we can probably remove o-ft-icons as as direct dependency of next/next-sass-setup/n-ui without further work.

Will any/all of your adding of o-icons to the above entail major releases?

**Comment by onishiweb** [comment]
Yes, most of those additions are major releases sadly, part of the spec is new dependencies require a major version.

**Comment by wheresrhys** [comment]
Have they already been released? I would say that'd be overzealous
application of that rule, which only exists because of the potential of
major version clashes. But with o-icons there is only one major version, so
no potential for a clash and a failed build service build.

On Wed, 25 May 2016 at 16:46 Adam Onishi notifications@github.com wrote:

> Yes, most of those additions are major releases sadly, part of the spec is
> new dependencies require a major version.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/Financial-Times/o-icons/issues/14#issuecomment-221615297

## 

---

_This email was sent by a company owned by Financial Times Group Limited 
("FT Group http://aboutus.ft.com/corporate-information/#axzz3rajCSIAt"), 
registered office at Number One Southwark Bridge, London SE1 9HL.  
Registered in England and Wales with company number 879531. This e-mail may 
contain confidential information. If you are not the intended recipient, 
please notify the sender immediately, delete all copies and do not 
distribute it further.  It could also contain personal views which are not 
necessarily those of the FT Group.  We may monitor outgoing or 
incoming emails as permitted by law._

**Comment by onishiweb** [comment]
They have. Because of the deprecation of `o-ft-icons` as well and some of the changes to the API in `o-icons` this would have needed to be the case anyway.

**Comment by wheresrhys** [comment]
fair enough. It'll probably be a bit longer though for us to wean ourselves off o-ft-icons

**Comment by alicebartlett** [comment]
@onishiweb can we close this issue yet?

**Comment by onishiweb** [comment]
I think it's waiting on @wheresrhys to upgrade Next's stuff away from `o-ft-icons`'s next branch? But in terms of Origami there's nothing much left to do.

**Comment by wheresrhys** [comment]
that's done. Didn't realise this was still open
