### ISSUE TITLE
vertical alignment — padding

### ISSUE THREAD

**Issue by gvonkoss** [Financial-Times/o-icons#58]
https://github.com/Financial-Times/o-icons/blob/fce1b73276a0811742559f9d92817a297f12cdea/scss/_mixins.scss#L70 seems to have been a solution for a time when the icons didn't all have padding, and did need to be aligned to the baseline, whereas now it seems like `vertical-align: middle;` would help avoid overrides in products that use this component.

**Comment by JakeChampion** [comment]
When trying to align an icon with some text @gvonkoss and myself found that `vertical-align: middle;` achieves this. We decided to override this inside of [o-expander](https://github.com/Financial-Times/o-expander/blob/c999c88d411103de554b5d5ab73a37b3b6382a4f/main.scss#L35), o-subs-card and [Next Article](https://github.com/Financial-Times/next-article/blob/3803a0ebab2e56db7be6a532e672c246abc09e2b/client/components/share/component.scss#L13) as well.

Making this change inside of o-icons would probably be a breaking change because some consumers would have solved the alignment issue by using absolute positioning and some magic numbers for margin and padding.

@alicebartlett, do you have any thoughts on this at all?

**Comment by alicebartlett** [comment]
Yes it would be breaking.
We should line this up for the next major (which is currently not planned)

**Comment by notlee** [comment]
The default has been set to `middle` here https://github.com/Financial-Times/o-icons/pull/89. To be released as part of the major cascade.
